### PR TITLE
Fixed Twitter date parsing in IE.

### PR DESCRIPTION
**Pull request by martijngastkemper**
Created a pull request for the solution proposed by @HartLarsson in #207. It a easier solution then proposed in #204.

### CODE REVIEW

**Comment by HartLarsson** [comment]
in a recent fix i've removed the 'en' localization to let people load the language they need

`post.dt_create = moment(element.created_at, 'dd MMM DD HH:mm:ss ZZ YYYY');`

**Comment by martijngastkemper** [comment]
Doesn't that change affect the parsing? I though it is necessary to detect the right language the date uses. Apparently it's not.

The locale is also defined when parsing RSS dates (https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L753). That would mean it can be removed there to.

**Comment by HartLarsson** [comment]
i've in my version removed the 'en' and works good:

`post.dt_create = moment(item.published, 'YYYY-MM-DDTHH:mm:ssZ');`

**Comment by martijngastkemper** [comment]
@HartLarsson I've removed the locale. English is the default locale so it doesn't make a difference.

**Pull request merged**
